name: "Recsyschallenge"
description: "The recsyschallenge description"

url: "http://localhost:4000"

permalink: pretty

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

navigation:
- text: Home
  url: "/"
- text: Challenge
  url: "/challenge/"
- text: Dataset
  url: "/dataset/"
- text: Prizes
  url: "/prizes/"
- text: Leaderboard
  url: "/leaderboard/"
- text: Rules
  url: "/rules/"
- text: Submission
  url: "/submissions/"
- text: Organizers
  url: "/organizers/"

