name: "Recsyschallenge"
description: "The recsyschallenge description"

url: "http://localhost:4000"

pygments: true
markdown: redcarpet2
permalink: pretty
navigation:
- text: Home
  url: "/"
- text: Challenge
  url: "/challenge/"
- text: Dataset
  url: "/dataset/"
- text: Leaderboard
  url: "/leaderboard/"
- text: Rules
  url: "/rules/"
- text: Organizers
  url: "/organizers/"
